name: Deploy to Server

on:
  push:
    branches: 'master'
  workflow_dispatch:
    
jobs:
  build_api:
    runs-on: self-hosted
    steps:
      - name: Setup
        uses: actions/checkout@v4
      - name: Deploy
        env: 
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          QRZ_USER: ${{ secrets.QRZ_USER }}
          QRZ_PASS: ${{ secrets.QRZ_PASS }}
        run: docker compose up --build -d
        
